# Generated by Django 5.2.5 on 2025-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='l_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='L Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='m_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='M Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='s_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='S Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='xl_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='XL Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='xs_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='XS Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='xxl_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='XXL Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='xxxl_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='XXXL Quantity'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
